# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    image: webdevops/php-apache:alpine-php7
    container_name: server-web-php
    ports:
      - 80:80
    #Still in development
    #environment:
    # - DB_IP=255.255.255.255
    volumes:
      - type: volume
        source: app
        target: /app/
  
volumes:
  mydata: